/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : JWT
 #	author : miyako
 #	2018/08/14
 #
 # --------------------------------------------------------------------------------*/

#include "openssl/crypto.h"
#include "openssl/hmac.h"
#include "openssl/evp.h"
#include "openssl/ssl.h"
#include "openssl/bio.h"
#include "openssl/buffer.h"
#include "openssl/pkcs12.h"
#include "openssl/err.h"

#include "json/json.h"

#include "josepp/b64.hpp"
#include "josepp/claims.hpp"
#include "josepp/crypto.hpp"
#include "josepp/digest.hpp"
#include "josepp/header.hpp"
#include "josepp/jws.hpp"
#include "josepp/tools.hpp"
#include "josepp/types.hpp"

// --- JWT
void JWT_Timestamp(sLONG_PTR *pResult, PackagePtr pParams);
void JWT_Sign(sLONG_PTR *pResult, PackagePtr pParams);
void JWT_Verify(sLONG_PTR *pResult, PackagePtr pParams);

void OnStartup(void);

#include <sys/timeb.h>  /* ftime, timeb (for timestamp in millisecond) */
#include <stdio.h> /* snprintf */

long long int getlld(C_TEXT &Param);
long long int getlld(std::string &num);

void convertFromString(std::string &fromString, C_TEXT &toString);
void convertToString(C_TEXT &fromString, std::string &toString);
